# Generated by Django 2.2.1 on 2019-05-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnote', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
